### ISSUE TITLE
[Q&A] May I know when will the code be released?

### ISSUE THREAD

**Issue by GHGmc2** [xinshuoweng/paradrive#1]
I noticed that it said "Code (Comming soon!)" on page https://xinshuoweng.github.io/paradrive/ three months ago, may I know if threre's plan to release the code?

Thanks for your work.

**Comment by zzj403** [comment]
Same question, eagerly awaiting the code release! @xinshuoweng

**Comment by BaophanN** [comment]
Hi, same question, does the author plan to release the code?
